# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `flipper-active_record` gem.
# Please instead update this file by running `bin/tapioca gem flipper-active_record`.


# source://flipper-active_record//lib/flipper/adapters/active_record.rb#5
module Flipper
  # source://forwardable/1.3.3/forwardable.rb#231
  def [](*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def actor(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def actors(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def adapter(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def add(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def bool(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def boolean(*args, **_arg1, &block); end

  # source://flipper/0.23.1/lib/flipper.rb#28
  def configuration; end

  # source://flipper/0.23.1/lib/flipper.rb#33
  def configuration=(configuration); end

  # source://flipper/0.23.1/lib/flipper.rb#23
  def configure; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def disable(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def disable_actor(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def disable_group(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def disable_percentage_of_actors(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def disable_percentage_of_time(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enable(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enable_actor(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enable_group(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enable_percentage_of_actors(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enable_percentage_of_time(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def enabled?(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def exist?(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def feature(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def features(*args, **_arg1, &block); end

  # source://flipper/0.23.1/lib/flipper.rb#128
  def group(name); end

  # source://flipper/0.23.1/lib/flipper.rb#115
  def group_exists?(name); end

  # source://flipper/0.23.1/lib/flipper.rb#101
  def group_names; end

  # source://flipper/0.23.1/lib/flipper.rb#94
  def groups; end

  # source://flipper/0.23.1/lib/flipper.rb#133
  def groups_registry; end

  # source://flipper/0.23.1/lib/flipper.rb#138
  def groups_registry=(registry); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def import(*args, **_arg1, &block); end

  # source://flipper/0.23.1/lib/flipper.rb#45
  def instance; end

  # source://flipper/0.23.1/lib/flipper.rb#52
  def instance=(flipper); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def memoize=(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def memoizing?(*args, **_arg1, &block); end

  # source://flipper/0.23.1/lib/flipper.rb#12
  def new(adapter, options = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def percentage_of_actors(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def percentage_of_time(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def preload(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def preload_all(*args, **_arg1, &block); end

  # source://flipper/0.23.1/lib/flipper.rb#85
  def register(name, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def remove(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def sync(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def sync_secret(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def time(*args, **_arg1, &block); end

  # source://flipper/0.23.1/lib/flipper.rb#108
  def unregister_groups; end
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#6
module Flipper::Adapters; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#7
class Flipper::Adapters::ActiveRecord
  include ::Flipper::Adapter
  extend ::Flipper::Adapter::ClassMethods

  # Public: Initialize a new ActiveRecord adapter instance.
  #
  # name - The Symbol name for this adapter. Optional (default :active_record)
  # feature_class - The AR class responsible for the features table.
  # gate_class - The AR class responsible for the gates table.
  #
  # Allowing the overriding of name is so you can differentiate multiple
  # instances of this adapter from each other, if, for some reason, that is
  # a thing you do.
  #
  # Allowing the overriding of the default feature/gate classes means you
  # can roll your own tables and what not, if you so desire.
  #
  # @return [ActiveRecord] a new instance of ActiveRecord
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#43
  def initialize(options = T.unsafe(nil)); end

  # Public: Adds a feature to the set of known features.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#55
  def add(feature); end

  # Public: Clears the gate values for a feature.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#80
  def clear(feature); end

  # Public: Disables a gate for a given thing.
  #
  # feature - The Flipper::Feature for the gate.
  # gate - The Flipper::Gate to disable.
  # thing - The Flipper::Type being disabled for the gate.
  #
  # Returns true.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#149
  def disable(feature, gate, thing); end

  # Public: Enables a gate for a given thing.
  #
  # feature - The Flipper::Feature for the gate.
  # gate - The Flipper::Gate to disable.
  # thing - The Flipper::Type being enabled for the gate.
  #
  # Returns true.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#127
  def enable(feature, gate, thing); end

  # Public: The set of known features.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#50
  def features; end

  # Public: Gets the values for all gates for a given feature.
  #
  # Returns a Hash of Flipper::Gate#key => value.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#88
  def get(feature); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#103
  def get_all; end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#93
  def get_multi(features); end

  # Public: The name of the adapter.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#29
  def name; end

  # Public: Removes a feature from the set of known features.
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#71
  def remove(feature); end

  # Private
  #
  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#165
  def unsupported_data_type(data_type); end

  private

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#191
  def enable_multi(feature, gate, thing); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#203
  def result_for_feature(feature, db_gates); end

  # source://flipper-active_record//lib/flipper/adapters/active_record.rb#171
  def set(feature, gate, thing, options = T.unsafe(nil)); end
end

# Private: Do not use outside of this adapter.
#
# source://flipper-active_record//lib/flipper/adapters/active_record.rb#11
class Flipper::Adapters::ActiveRecord::Feature < ::ActiveRecord::Base
  include ::Flipper::Adapters::ActiveRecord::Feature::GeneratedAttributeMethods
  include ::Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods

  class << self
    # source://activemodel/7.0.8.4/lib/active_model/validations.rb#52
    def _validators; end

    # source://activerecord/7.0.8.4/lib/active_record/enum.rb#116
    def defined_enums; end
  end
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#0
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAssociationMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#0
module Flipper::Adapters::ActiveRecord::Feature::GeneratedAttributeMethods; end

# Private: Do not use outside of this adapter.
#
# source://flipper-active_record//lib/flipper/adapters/active_record.rb#20
class Flipper::Adapters::ActiveRecord::Gate < ::ActiveRecord::Base
  include ::Flipper::Adapters::ActiveRecord::Gate::GeneratedAttributeMethods
  include ::Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods

  class << self
    # source://activemodel/7.0.8.4/lib/active_model/validations.rb#52
    def _validators; end

    # source://activerecord/7.0.8.4/lib/active_record/enum.rb#116
    def defined_enums; end
  end
end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#0
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAssociationMethods; end

# source://flipper-active_record//lib/flipper/adapters/active_record.rb#0
module Flipper::Adapters::ActiveRecord::Gate::GeneratedAttributeMethods; end
