# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `googleauth` gem.
# Please instead update this file by running `bin/tapioca gem googleauth`.


# source://googleauth//lib/googleauth/compute_engine.rb#19
module Google; end

# Module Auth provides classes that provide Google-specific authorization
# used to access Google APIs.
#
# source://googleauth//lib/googleauth/compute_engine.rb#22
module Google::Auth
  private

  # Obtains the default credentials implementation to use in this
  # environment.
  #
  # Use this to obtain the Application Default Credentials for accessing
  # Google APIs.  Application Default Credentials are described in detail
  # at https://cloud.google.com/docs/authentication/production.
  #
  # If supplied, scope is used to create the credentials instance, when it can
  # be applied.  E.g, on google compute engine and for user credentials the
  # scope is ignored.
  #
  # @param scope [string|array|nil] the scope(s) to access
  # @param options [Hash] Connection options. These may be used to configure
  #   the `Faraday::Connection` used for outgoing HTTP requests. For
  #   example, if a connection proxy must be used in the current network,
  #   you may provide a connection with with the needed proxy options.
  #   The following keys are recognized:
  #   * `:default_connection` The connection object to use for token
  #   refresh requests.
  #   * `:connection_builder` A `Proc` that creates and returns a
  #   connection to use for token refresh requests.
  #   * `:connection` The connection to use to determine whether GCE
  #   metadata credentials are available.
  #
  # source://googleauth//lib/googleauth/application_default.rb#53
  def get_application_default(scope = T.unsafe(nil), options = T.unsafe(nil)); end

  class << self
    # Obtains the default credentials implementation to use in this
    # environment.
    #
    # Use this to obtain the Application Default Credentials for accessing
    # Google APIs.  Application Default Credentials are described in detail
    # at https://cloud.google.com/docs/authentication/production.
    #
    # If supplied, scope is used to create the credentials instance, when it can
    # be applied.  E.g, on google compute engine and for user credentials the
    # scope is ignored.
    #
    # @param scope [string|array|nil] the scope(s) to access
    # @param options [Hash] Connection options. These may be used to configure
    #   the `Faraday::Connection` used for outgoing HTTP requests. For
    #   example, if a connection proxy must be used in the current network,
    #   you may provide a connection with with the needed proxy options.
    #   The following keys are recognized:
    #   * `:default_connection` The connection object to use for token
    #   refresh requests.
    #   * `:connection_builder` A `Proc` that creates and returns a
    #   connection to use for token refresh requests.
    #   * `:connection` The connection to use to determine whether GCE
    #   metadata credentials are available.
    #
    # source://googleauth//lib/googleauth/application_default.rb#53
    def get_application_default(scope = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

# Representation of an application's identity for user authorization
# flows.
#
# source://googleauth//lib/googleauth/client_id.rb#22
class Google::Auth::ClientId
  # Initialize the Client ID
  #
  # @note Direction instantion is discouraged to avoid embedding IDs
  #   & secrets in source. See {#from_file} to load from
  #   `client_secrets.json` files.
  # @param id [String] Text identifier of the client ID
  # @param secret [String] Secret associated with the client ID
  # @return [ClientId] a new instance of ClientId
  #
  # source://googleauth//lib/googleauth/client_id.rb#51
  def initialize(id, secret); end

  # Text identifier of the client ID
  #
  # @return [String]
  #
  # source://googleauth//lib/googleauth/client_id.rb#32
  def id; end

  # Secret associated with the client ID
  #
  # @return [String]
  #
  # source://googleauth//lib/googleauth/client_id.rb#36
  def secret; end

  class << self
    # Returns the value of attribute default.
    #
    # source://googleauth//lib/googleauth/client_id.rb#39
    def default; end

    # Sets the attribute default
    #
    # @param value the value to set the attribute default to.
    #
    # source://googleauth//lib/googleauth/client_id.rb#39
    def default=(_arg0); end

    # Constructs a Client ID from a JSON file downloaded from the
    # Google Developers Console.
    #
    # @param file [String, File] Path of file to read from
    # @return [Google::Auth::ClientID]
    #
    # source://googleauth//lib/googleauth/client_id.rb#65
    def from_file(file); end

    # Constructs a Client ID from a previously loaded JSON file. The hash
    # structure should
    # match the expected JSON format.
    #
    # @param config [hash] Parsed contents of the JSON file
    # @raise [MISSING_TOP_LEVEL_ELEMENT_ERROR]
    # @return [Google::Auth::ClientID]
    #
    # source://googleauth//lib/googleauth/client_id.rb#81
    def from_hash(config); end
  end
end

# source://googleauth//lib/googleauth/client_id.rb#25
Google::Auth::ClientId::CLIENT_ID = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/client_id.rb#26
Google::Auth::ClientId::CLIENT_SECRET = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/client_id.rb#23
Google::Auth::ClientId::INSTALLED_APP = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/client_id.rb#27
Google::Auth::ClientId::MISSING_TOP_LEVEL_ELEMENT_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/client_id.rb#24
Google::Auth::ClientId::WEB_APP = T.let(T.unsafe(nil), String)

# Credentials is a high-level base class used by Google's API client
# libraries to represent the authentication when connecting to an API.
# In most cases, it is subclassed by API-specific credential classes that
# can be instantiated by clients.
#
# ## Options
#
# Credentials classes are configured with options that dictate default
# values for parameters such as scope and audience. These defaults are
# expressed as class attributes, and may differ from endpoint to endpoint.
# Normally, an API client will provide subclasses specific to each
# endpoint, configured with appropriate values.
#
# Note that these options inherit up the class hierarchy. If a particular
# options is not set for a subclass, its superclass is queried.
#
# Some older users of this class set options via constants. This usage is
# deprecated. For example, instead of setting the `AUDIENCE` constant on
# your subclass, call the `audience=` method.
#
# ## Example
#
#     class MyCredentials < Google::Auth::Credentials
#       # Set the default scope for these credentials
#       self.scope = "http://example.com/my_scope"
#     end
#
#     # creds is a credentials object suitable for Google API clients
#     creds = MyCredentials.default
#     creds.scope  # => ["http://example.com/my_scope"]
#
#     class SubCredentials < MyCredentials
#       # Override the default scope for this subclass
#       self.scope = "http://example.com/sub_scope"
#     end
#
#     creds2 = SubCredentials.default
#     creds2.scope  # => ["http://example.com/sub_scope"]
#
# source://googleauth//lib/googleauth/credentials.rb#63
class Google::Auth::Credentials
  extend ::Forwardable

  # Creates a new Credentials instance with the provided auth credentials, and with the default
  # values configured on the class.
  #
  # @param keyfile [String, Hash, Signet::OAuth2::Client] The keyfile can be provided as one of the following:
  #
  #   * The path to a JSON keyfile (as a +String+)
  #   * The contents of a JSON keyfile (as a +Hash+)
  #   * A +Signet::OAuth2::Client+ object
  # @param options [Hash] The options for configuring the credentials instance. The following is supported:
  #
  #   * +:scope+ - the scope for the client
  #   * +"project_id"+ (and optionally +"project"+) - the project identifier for the client
  #   * +:connection_builder+ - the connection builder to use for the client
  #   * +:default_connection+ - the default connection to use for the client
  # @return [Credentials] a new instance of Credentials
  #
  # source://googleauth//lib/googleauth/credentials.rb#353
  def initialize(keyfile, options = T.unsafe(nil)); end

  # @return [String] The target audience ID when issuing assertions. Used only by the
  #   assertion grant type.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def audience(*args, **_arg1, &block); end

  # The Signet::OAuth2::Client object the Credentials instance is using.
  #
  # @return [Signet::OAuth2::Client]
  #
  # source://googleauth//lib/googleauth/credentials.rb#286
  def client; end

  # The Signet::OAuth2::Client object the Credentials instance is using.
  #
  # @return [Signet::OAuth2::Client]
  #
  # source://googleauth//lib/googleauth/credentials.rb#286
  def client=(_arg0); end

  # @return [String] The issuer ID associated with this client.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def issuer(*args, **_arg1, &block); end

  # Identifier for the project the client is authenticating with.
  #
  # @return [String]
  #
  # source://googleauth//lib/googleauth/credentials.rb#293
  def project_id; end

  # Identifier for a separate project used for billing/quota, if any.
  #
  # @return [String, nil]
  #
  # source://googleauth//lib/googleauth/credentials.rb#300
  def quota_project_id; end

  # @return [String, Array<String>] The scope for this client. A scope is an access range
  #   defined by the authorization server. The scope can be a single value or a list of values.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def scope(*args, **_arg1, &block); end

  # @return [String, OpenSSL::PKey] The signing key associated with this client.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def signing_key(*args, **_arg1, &block); end

  # @return [String] The final target audience for ID tokens returned by this credential.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def target_audience(*args, **_arg1, &block); end

  # @return [String] The token credential URI. The URI is the authorization server's HTTP
  #   endpoint capable of issuing tokens and refreshing expired tokens.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def token_credential_uri(*args, **_arg1, &block); end

  # @return [Proc] Returns a reference to the {Signet::OAuth2::Client#apply} method,
  #   suitable for passing as a closure.
  #
  # source://forwardable/1.3.3/forwardable.rb#231
  def updater_proc(*args, **_arg1, &block); end

  protected

  # source://googleauth//lib/googleauth/credentials.rb#497
  def client_options(options); end

  # Initializes the Signet client.
  #
  # source://googleauth//lib/googleauth/credentials.rb#484
  def init_client(keyfile, connection_options = T.unsafe(nil)); end

  # returns a new Hash with string keys instead of symbol keys.
  #
  # source://googleauth//lib/googleauth/credentials.rb#491
  def stringify_hash_keys(hash); end

  # source://googleauth//lib/googleauth/credentials.rb#535
  def update_from_filepath(path, options); end

  # source://googleauth//lib/googleauth/credentials.rb#526
  def update_from_hash(hash, options); end

  # source://googleauth//lib/googleauth/credentials.rb#520
  def update_from_signet(client); end

  # Verify that the keyfile argument is a file.
  #
  # source://googleauth//lib/googleauth/credentials.rb#478
  def verify_keyfile_exists!(keyfile); end

  # Verify that the keyfile argument is provided.
  #
  # source://googleauth//lib/googleauth/credentials.rb#472
  def verify_keyfile_provided!(keyfile); end

  class << self
    # The default target audience ID to be used when none is provided during initialization.
    # Used only by the assertion grant type.
    #
    # @return [String]
    #
    # source://googleauth//lib/googleauth/credentials.rb#102
    def audience; end

    # Sets the default target audience ID to be used when none is provided during initialization.
    #
    # @param new_audience [String]
    #
    # source://googleauth//lib/googleauth/credentials.rb#113
    def audience=(new_audience); end

    # Creates a new Credentials instance with auth credentials acquired by searching the
    # environment variables and paths configured on the class, and with the default values
    # configured on the class.
    #
    # The auth credentials are searched for in the following order:
    #
    # 1. configured environment variables (see {Credentials.env_vars})
    # 2. configured default file paths (see {Credentials.paths})
    # 3. application default (see {Google::Auth.get_application_default})
    #
    # @param options [Hash] The options for configuring the credentials instance. The following is supported:
    #
    #   * +:scope+ - the scope for the client
    #   * +"project_id"+ (and optionally +"project"+) - the project identifier for the client
    #   * +:connection_builder+ - the connection builder to use for the client
    #   * +:default_connection+ - the default connection to use for the client
    # @return [Credentials]
    #
    # source://googleauth//lib/googleauth/credentials.rb#394
    def default(options = T.unsafe(nil)); end

    # The environment variables to search for credentials. Values can either be a file path to the
    # credentials file, or the JSON contents of the credentials file.
    # The env_vars will never be nil. If there are no vars, the empty array is returned.
    #
    # @return [Array<String>]
    #
    # source://googleauth//lib/googleauth/credentials.rb#184
    def env_vars; end

    # Sets the environment variables to search for credentials.
    # Setting to `nil` "unsets" the value, and defaults to the superclass
    # (or to the empty array if there is no superclass).
    #
    # @param new_env_vars [String, Array<String>, nil]
    #
    # source://googleauth//lib/googleauth/credentials.rb#208
    def env_vars=(new_env_vars); end

    # Internal recursive lookup for env_vars.
    #
    # @private
    #
    # source://googleauth//lib/googleauth/credentials.rb#192
    def env_vars_internal; end

    # Return the given parameter value, defaulting up the class hierarchy.
    #
    # First returns the value of the instance variable, if set.
    # Next, calls the given block if provided. (This is generally used to
    # look up legacy constant-based values.)
    # Otherwise, calls the superclass method if present.
    # Returns nil if all steps fail.
    #
    # @param name [Symbol] The parameter name
    # @param method_name [Symbol] The lookup method name, if different
    # @private
    # @return [Object] The value
    #
    # source://googleauth//lib/googleauth/credentials.rb#261
    def lookup_auth_param(name, method_name = T.unsafe(nil)); end

    # Return the value of the given constant if it is defined directly in
    # this class, or nil if not.
    #
    # @param Name [Symbol] of the constant
    # @private
    # @return [Object] The value
    #
    # source://googleauth//lib/googleauth/credentials.rb#277
    def lookup_local_constant(name); end

    # The file paths to search for credentials files.
    # The paths will never be nil. If there are no paths, the empty array is returned.
    #
    # @return [Array<String>]
    #
    # source://googleauth//lib/googleauth/credentials.rb#219
    def paths; end

    # Set the file paths to search for credentials files.
    # Setting to `nil` "unsets" the value, and defaults to the superclass
    # (or to the empty array if there is no superclass).
    #
    # @param new_paths [String, Array<String>, nil]
    #
    # source://googleauth//lib/googleauth/credentials.rb#242
    def paths=(new_paths); end

    # Internal recursive lookup for paths.
    #
    # @private
    #
    # source://googleauth//lib/googleauth/credentials.rb#227
    def paths_internal; end

    # The default scope to be used when none is provided during initialization.
    # A scope is an access range defined by the authorization server.
    # The scope can be a single value or a list of values.
    #
    # Either {#scope} or {#target_audience}, but not both, should be non-nil.
    # If {#scope} is set, this credential will produce access tokens.
    # If {#target_audience} is set, this credential will produce ID tokens.
    #
    # @return [String, Array<String>, nil]
    #
    # source://googleauth//lib/googleauth/credentials.rb#128
    def scope; end

    # Sets the default scope to be used when none is provided during initialization.
    #
    # Either {#scope} or {#target_audience}, but not both, should be non-nil.
    # If {#scope} is set, this credential will produce access tokens.
    # If {#target_audience} is set, this credential will produce ID tokens.
    #
    # @param new_scope [String, Array<String>, nil]
    #
    # source://googleauth//lib/googleauth/credentials.rb#144
    def scope=(new_scope); end

    # The default final target audience for ID tokens, to be used when none
    # is provided during initialization.
    #
    # Either {#scope} or {#target_audience}, but not both, should be non-nil.
    # If {#scope} is set, this credential will produce access tokens.
    # If {#target_audience} is set, this credential will produce ID tokens.
    #
    # @return [String, nil]
    #
    # source://googleauth//lib/googleauth/credentials.rb#159
    def target_audience; end

    # Sets the default final target audience for ID tokens, to be used when none
    # is provided during initialization.
    #
    # Either {#scope} or {#target_audience}, but not both, should be non-nil.
    # If {#scope} is set, this credential will produce access tokens.
    # If {#target_audience} is set, this credential will produce ID tokens.
    #
    # @param new_target_audience [String, nil]
    #
    # source://googleauth//lib/googleauth/credentials.rb#173
    def target_audience=(new_target_audience); end

    # The default token credential URI to be used when none is provided during initialization.
    # The URI is the authorization server's HTTP endpoint capable of issuing tokens and
    # refreshing expired tokens.
    #
    # @return [String]
    #
    # source://googleauth//lib/googleauth/credentials.rb#81
    def token_credential_uri; end

    # Set the default token credential URI to be used when none is provided during initialization.
    #
    # @param new_token_credential_uri [String]
    #
    # source://googleauth//lib/googleauth/credentials.rb#92
    def token_credential_uri=(new_token_credential_uri); end

    private

    # @private Lookup Credentials using Google::Auth.get_application_default.
    #
    # source://googleauth//lib/googleauth/credentials.rb#438
    def from_application_default(options); end

    # @private Lookup Credentials from default file paths.
    #
    # source://googleauth//lib/googleauth/credentials.rb#427
    def from_default_paths(options); end

    # @private Lookup Credentials from environment variables.
    #
    # source://googleauth//lib/googleauth/credentials.rb#408
    def from_env_vars(options); end

    # @private Read credentials from a JSON stream.
    #
    # source://googleauth//lib/googleauth/credentials.rb#451
    def from_io(io, options); end
  end
end

# The default target audience ID to be used when none is provided during initialization.
#
# source://googleauth//lib/googleauth/credentials.rb#70
Google::Auth::Credentials::AUDIENCE = T.let(T.unsafe(nil), String)

# The default token credential URI to be used when none is provided during initialization.
#
# source://googleauth//lib/googleauth/credentials.rb#66
Google::Auth::Credentials::TOKEN_CREDENTIAL_URI = T.let(T.unsafe(nil), String)

# CredentialsLoader contains the behaviour used to locate and find default
# credentials files on the file system.
#
# source://googleauth//lib/googleauth/credentials_loader.rb#24
module Google::Auth::CredentialsLoader
  # Creates an instance from the path specified in an environment
  # variable.
  #
  # @param scope [string|array|nil] the scope(s) to access
  # @param options [Hash] Connection options. These may be used to configure
  #   how OAuth tokens are retrieved, by providing a suitable
  #   `Faraday::Connection`. For example, if a connection proxy must be
  #   used in the current network, you may provide a connection with
  #   with the needed proxy options.
  #   The following keys are recognized:
  #   * `:default_connection` The connection object to use.
  #   * `:connection_builder` A `Proc` that returns a connection.
  #
  # source://googleauth//lib/googleauth/credentials_loader.rb#76
  def from_env(scope = T.unsafe(nil), options = T.unsafe(nil)); end

  # Creates an instance from the system default path
  #
  # @param scope [string|array|nil] the scope(s) to access
  # @param options [Hash] Connection options. These may be used to configure
  #   how OAuth tokens are retrieved, by providing a suitable
  #   `Faraday::Connection`. For example, if a connection proxy must be
  #   used in the current network, you may provide a connection with
  #   with the needed proxy options.
  #   The following keys are recognized:
  #   * `:default_connection` The connection object to use.
  #   * `:connection_builder` A `Proc` that returns a connection.
  #
  # source://googleauth//lib/googleauth/credentials_loader.rb#128
  def from_system_default_path(scope = T.unsafe(nil), options = T.unsafe(nil)); end

  # Creates an instance from a well known path.
  #
  # @param scope [string|array|nil] the scope(s) to access
  # @param options [Hash] Connection options. These may be used to configure
  #   how OAuth tokens are retrieved, by providing a suitable
  #   `Faraday::Connection`. For example, if a connection proxy must be
  #   used in the current network, you may provide a connection with
  #   with the needed proxy options.
  #   The following keys are recognized:
  #   * `:default_connection` The connection object to use.
  #   * `:connection_builder` A `Proc` that returns a connection.
  #
  # source://googleauth//lib/googleauth/credentials_loader.rb#102
  def from_well_known_path(scope = T.unsafe(nil), options = T.unsafe(nil)); end

  # make_creds proxies the construction of a credentials instance
  #
  # By default, it calls #new on the current class, but this behaviour can
  # be modified, allowing different instances to be created.
  #
  # source://googleauth//lib/googleauth/credentials_loader.rb#58
  def make_creds(*args); end

  private

  # source://googleauth//lib/googleauth/credentials_loader.rb#180
  def authorized_user_env_vars?; end

  # source://googleauth//lib/googleauth/credentials_loader.rb#166
  def interpret_options(scope, options); end

  # Finds project_id from gcloud CLI configuration
  #
  # source://googleauth//lib/googleauth/credentials_loader.rb#154
  def load_gcloud_project_id; end

  # source://googleauth//lib/googleauth/credentials_loader.rb#175
  def service_account_env_vars?; end

  # Issues warning if cloud sdk client id is used
  #
  # source://googleauth//lib/googleauth/credentials_loader.rb#148
  def warn_if_cloud_sdk_credentials(client_id); end

  class << self
    # Finds project_id from gcloud CLI configuration
    #
    # source://googleauth//lib/googleauth/credentials_loader.rb#154
    def load_gcloud_project_id; end

    # Issues warning if cloud sdk client id is used
    #
    # source://googleauth//lib/googleauth/credentials_loader.rb#148
    def warn_if_cloud_sdk_credentials(client_id); end
  end
end

# source://googleauth//lib/googleauth/credentials_loader.rb#31
Google::Auth::CredentialsLoader::ACCOUNT_TYPE_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#27
Google::Auth::CredentialsLoader::CLIENT_EMAIL_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#28
Google::Auth::CredentialsLoader::CLIENT_ID_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#29
Google::Auth::CredentialsLoader::CLIENT_SECRET_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#44
Google::Auth::CredentialsLoader::CLOUD_SDK_CLIENT_ID = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#47
Google::Auth::CredentialsLoader::CLOUD_SDK_CREDENTIALS_WARNING = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#37
Google::Auth::CredentialsLoader::CREDENTIALS_FILE_NAME = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#25
Google::Auth::CredentialsLoader::ENV_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#35
Google::Auth::CredentialsLoader::GCLOUD_CONFIG_COMMAND = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#33
Google::Auth::CredentialsLoader::GCLOUD_POSIX_COMMAND = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#34
Google::Auth::CredentialsLoader::GCLOUD_WINDOWS_COMMAND = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#38
Google::Auth::CredentialsLoader::NOT_FOUND_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#26
Google::Auth::CredentialsLoader::PRIVATE_KEY_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#32
Google::Auth::CredentialsLoader::PROJECT_ID_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#30
Google::Auth::CredentialsLoader::REFRESH_TOKEN_VAR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#42
Google::Auth::CredentialsLoader::SYSTEM_DEFAULT_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#40
Google::Auth::CredentialsLoader::WELL_KNOWN_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/credentials_loader.rb#39
Google::Auth::CredentialsLoader::WELL_KNOWN_PATH = T.let(T.unsafe(nil), String)

# DefaultCredentials is used to preload the credentials file, to determine
# which type of credentials should be loaded.
#
# source://googleauth//lib/googleauth/default_credentials.rb#28
class Google::Auth::DefaultCredentials
  extend ::Google::Auth::CredentialsLoader

  class << self
    # Reads the input json and determines which creds class to use.
    #
    # source://googleauth//lib/googleauth/default_credentials.rb#62
    def determine_creds_class(json_key_io); end

    # override CredentialsLoader#make_creds to use the class determined by
    # loading the json.
    #
    # source://googleauth//lib/googleauth/default_credentials.rb#33
    def make_creds(options = T.unsafe(nil)); end

    # source://googleauth//lib/googleauth/default_credentials.rb#47
    def read_creds; end
  end
end

# Extends Signet::OAuth2::Client so that the auth token is obtained from
# the GCE metadata server.
#
# source://googleauth//lib/googleauth/compute_engine.rb#36
class Google::Auth::GCECredentials < ::Signet::OAuth2::Client
  extend ::Memoist::InstanceMethods

  # Overrides the super class method to change how access tokens are
  # fetched.
  #
  # source://googleauth//lib/googleauth/compute_engine.rb#90
  def fetch_access_token(options = T.unsafe(nil)); end

  class << self
    # source://googleauth//lib/googleauth/compute_engine.rb#71
    def _unmemoized_on_gce?(options = T.unsafe(nil)); end

    # source://googleauth//lib/googleauth/compute_engine.rb#61
    def compute_auth_token_uri; end

    # source://googleauth//lib/googleauth/compute_engine.rb#57
    def compute_check_uri; end

    # source://googleauth//lib/googleauth/compute_engine.rb#65
    def compute_id_token_uri; end

    # source://googleauth//lib/googleauth/compute_engine.rb#53
    def metadata_host; end

    # Detect if this appear to be a GCE instance, by checking if metadata
    # is available.
    #
    # @return [Boolean]
    #
    # source://memoist/0.16.2/lib/memoist.rb#206
    def on_gce?(*args); end
  end
end

# @private Unused and deprecated
#
# source://googleauth//lib/googleauth/compute_engine.rb#42
Google::Auth::GCECredentials::COMPUTE_AUTH_TOKEN_URI = T.let(T.unsafe(nil), String)

# @private Unused and deprecated
#
# source://googleauth//lib/googleauth/compute_engine.rb#48
Google::Auth::GCECredentials::COMPUTE_CHECK_URI = T.let(T.unsafe(nil), String)

# @private Unused and deprecated
#
# source://googleauth//lib/googleauth/compute_engine.rb#45
Google::Auth::GCECredentials::COMPUTE_ID_TOKEN_URI = T.let(T.unsafe(nil), String)

# The IP Address is used in the URIs to speed up failures on non-GCE
# systems.
#
# source://googleauth//lib/googleauth/compute_engine.rb#39
Google::Auth::GCECredentials::DEFAULT_METADATA_HOST = T.let(T.unsafe(nil), String)

# ## Verifying Google ID tokens
#
# This module verifies ID tokens issued by Google. This can be used to
# authenticate signed-in users using OpenID Connect. See
# https://developers.google.com/identity/sign-in/web/backend-auth for more
# information.
#
# ### Basic usage
#
# To verify an ID token issued by Google accounts:
#
#     payload = Google::Auth::IDTokens.verify_oidc the_token,
#                                                  aud: "my-app-client-id"
#
# If verification succeeds, you will receive the token's payload as a hash.
# If verification fails, an exception (normally a subclass of
# {Google::Auth::IDTokens::VerificationError}) will be raised.
#
# To verify an ID token issued by the Google identity-aware proxy (IAP):
#
#     payload = Google::Auth::IDTokens.verify_iap the_token,
#                                                 aud: "my-app-client-id"
#
# These methods will automatically download and cache the Google public
# keys necessary to verify these tokens. They will also automatically
# verify the issuer (`iss`) field for their respective types of ID tokens.
#
# ### Advanced usage
#
# If you want to provide your own public keys, either by pointing at a
# custom URI or by providing the key data directly, use the Verifier class
# and pass in a key source.
#
# To point to a custom URI that returns a JWK set:
#
#     source = Google::Auth::IDTokens::JwkHttpKeySource.new "https://example.com/jwk"
#     verifier = Google::Auth::IDTokens::Verifier.new key_source: source
#     payload = verifier.verify the_token, aud: "my-app-client-id"
#
# To provide key data directly:
#
#     jwk_data = {
#       keys: [
#         {
#           alg: "ES256",
#           crv: "P-256",
#           kid: "LYyP2g",
#           kty: "EC",
#           use: "sig",
#           x: "SlXFFkJ3JxMsXyXNrqzE3ozl_0913PmNbccLLWfeQFU",
#           y: "GLSahrZfBErmMUcHP0MGaeVnJdBwquhrhQ8eP05NfCI"
#         }
#       ]
#     }
#     source = Google::Auth::IDTokens::StaticKeySource.from_jwk_set jwk_data
#     verifier = Google::Auth::IDTokens::Verifier key_source: source
#     payload = verifier.verify the_token, aud: "my-app-client-id"
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#20
module Google::Auth::IDTokens
  class << self
    # Reset all convenience key sources. Used for testing.
    #
    # @private
    #
    # source://googleauth//lib/googleauth/id_tokens.rb#136
    def forget_sources!; end

    # The key source providing public keys that can be used to verify
    # ID tokens issued by Google IAP.
    #
    # @return [Google::Auth::IDTokens::JwkHttpKeySource]
    #
    # source://googleauth//lib/googleauth/id_tokens.rb#128
    def iap_key_source; end

    # The key source providing public keys that can be used to verify
    # ID tokens issued by Google OIDC.
    #
    # @return [Google::Auth::IDTokens::JwkHttpKeySource]
    #
    # source://googleauth//lib/googleauth/id_tokens.rb#118
    def oidc_key_source; end

    # A convenience method that verifies a token allegedly issued by Google
    # IAP.
    #
    # @param token [String] The ID token to verify
    # @param aud [String, Array<String>, nil] The expected audience. At least
    #   one `aud` field in the token must match at least one of the
    #   provided audiences, or the verification will fail with
    #   {Google::Auth::IDToken::AudienceMismatchError}. If `nil` (the
    #   default), no audience checking is performed.
    # @param azp [String, Array<String>, nil] The expected authorized party
    #   (azp). At least one `azp` field in the token must match at least
    #   one of the provided values, or the verification will fail with
    #   {Google::Auth::IDToken::AuthorizedPartyMismatchError}. If `nil`
    #   (the default), no azp checking is performed.
    # @param aud [String, Array<String>, nil] The expected audience. At least
    #   one `iss` field in the token must match at least one of the
    #   provided issuers, or the verification will fail with
    #   {Google::Auth::IDToken::IssuerMismatchError}. If `nil`, no issuer
    #   checking is performed. Default is to check against {IAP_ISSUERS}.
    # @raise [KeySourceError] if the key source failed to obtain public keys
    # @raise [VerificationError] if the token verification failed.
    #   Additional data may be available in the error subclass and message.
    # @return [Hash] The decoded token payload.
    #
    # source://googleauth//lib/googleauth/id_tokens.rb#205
    def verify_iap(token, aud: T.unsafe(nil), azp: T.unsafe(nil), iss: T.unsafe(nil)); end

    # A convenience method that verifies a token allegedly issued by Google
    # OIDC.
    #
    # @param token [String] The ID token to verify
    # @param aud [String, Array<String>, nil] The expected audience. At least
    #   one `aud` field in the token must match at least one of the
    #   provided audiences, or the verification will fail with
    #   {Google::Auth::IDToken::AudienceMismatchError}. If `nil` (the
    #   default), no audience checking is performed.
    # @param azp [String, Array<String>, nil] The expected authorized party
    #   (azp). At least one `azp` field in the token must match at least
    #   one of the provided values, or the verification will fail with
    #   {Google::Auth::IDToken::AuthorizedPartyMismatchError}. If `nil`
    #   (the default), no azp checking is performed.
    # @param aud [String, Array<String>, nil] The expected audience. At least
    #   one `iss` field in the token must match at least one of the
    #   provided issuers, or the verification will fail with
    #   {Google::Auth::IDToken::IssuerMismatchError}. If `nil`, no issuer
    #   checking is performed. Default is to check against {OIDC_ISSUERS}.
    # @raise [KeySourceError] if the key source failed to obtain public keys
    # @raise [VerificationError] if the token verification failed.
    #   Additional data may be available in the error subclass and message.
    # @return [Hash] The decoded token payload.
    #
    # source://googleauth//lib/googleauth/id_tokens.rb#167
    def verify_oidc(token, aud: T.unsafe(nil), azp: T.unsafe(nil), iss: T.unsafe(nil)); end
  end
end

# A key source that aggregates other key sources. This means it will
# aggregate the keys provided by its constituent sources. Additionally,
# when asked to refresh, it will refresh all its constituent sources.
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#351
class Google::Auth::IDTokens::AggregateKeySource
  # Create a key source that aggregates other key sources.
  #
  # @param sources [Array<key source>] The key sources to aggregate.
  # @return [AggregateKeySource] a new instance of AggregateKeySource
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#357
  def initialize(sources); end

  # Return the current keys, without attempting to refresh.
  #
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#366
  def current_keys; end

  # Attempt to refresh keys and return the new keys.
  #
  # @raise [KeySourceError] if key retrieval failed.
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#376
  def refresh_keys; end
end

# Failed to verify a token because its audience did not match.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#49
class Google::Auth::IDTokens::AudienceMismatchError < ::Google::Auth::IDTokens::VerificationError; end

# Failed to verify a token because its authorized party did not match.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#54
class Google::Auth::IDTokens::AuthorizedPartyMismatchError < ::Google::Auth::IDTokens::VerificationError; end

# Failed to verify a token because it is expired.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#34
class Google::Auth::IDTokens::ExpiredTokenError < ::Google::Auth::IDTokens::VerificationError; end

# A base key source that downloads keys from a URI. Subclasses should
# override {HttpKeySource#interpret_json} to parse the response.
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#222
class Google::Auth::IDTokens::HttpKeySource
  # Create an HTTP key source.
  #
  # @param uri [String, URI] The URI from which to download keys.
  # @param retry_interval [Integer, nil] Override the retry interval in
  #   seconds. This is the minimum time between retries of failed key
  #   downloads.
  # @return [HttpKeySource] a new instance of HttpKeySource
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#238
  def initialize(uri, retry_interval: T.unsafe(nil)); end

  # Return the current keys, without attempting to re-download.
  #
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#257
  def current_keys; end

  # Attempt to re-download keys (if the retry interval has expired) and
  # return the new keys.
  #
  # @raise [KeySourceError] if key retrieval failed.
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#266
  def refresh_keys; end

  # The URI from which to download keys.
  #
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#250
  def uri; end

  protected

  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#286
  def interpret_json(_data); end
end

# The default interval between retries in seconds (3600s = 1hr).
#
# @return [Integer]
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#228
Google::Auth::IDTokens::HttpKeySource::DEFAULT_RETRY_INTERVAL = T.let(T.unsafe(nil), Integer)

# A list of issuers expected for Google IAP-issued tokens.
#
# @return [Array<String>]
#
# source://googleauth//lib/googleauth/id_tokens.rb#95
Google::Auth::IDTokens::IAP_ISSUERS = T.let(T.unsafe(nil), Array)

# The URL for Google IAP public keys
#
# @return [String]
#
# source://googleauth//lib/googleauth/id_tokens.rb#109
Google::Auth::IDTokens::IAP_JWK_URL = T.let(T.unsafe(nil), String)

# Failed to verify a token because its issuer did not match.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#44
class Google::Auth::IDTokens::IssuerMismatchError < ::Google::Auth::IDTokens::VerificationError; end

# A key source that downloads a JWK set.
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#326
class Google::Auth::IDTokens::JwkHttpKeySource < ::Google::Auth::IDTokens::HttpKeySource
  # Create a key source that downloads a JWT Set.
  #
  # @param uri [String, URI] The URI from which to download keys.
  # @param retry_interval [Integer, nil] Override the retry interval in
  #   seconds. This is the minimum time between retries of failed key
  #   downloads.
  # @return [JwkHttpKeySource] a new instance of JwkHttpKeySource
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#335
  def initialize(uri, retry_interval: T.unsafe(nil)); end

  protected

  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#341
  def interpret_json(data); end
end

# A public key used for verifying ID tokens.
#
# This includes the public key data, ID, and the algorithm used for
# signature verification. RSA and Elliptical Curve (EC) keys are
# supported.
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#36
class Google::Auth::IDTokens::KeyInfo
  # Create a public key info structure.
  #
  # @param id [String] The key ID.
  # @param key [OpenSSL::PKey::RSA, OpenSSL::PKey::EC] The key itself.
  # @param algorithm [String] The algorithm (normally `RS256` or `ES256`)
  # @return [KeyInfo] a new instance of KeyInfo
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#44
  def initialize(id: T.unsafe(nil), key: T.unsafe(nil), algorithm: T.unsafe(nil)); end

  # The signature algorithm. (normally `RS256` or `ES256`)
  #
  # @return [String]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#66
  def algorithm; end

  # The key ID.
  #
  # @return [String]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#54
  def id; end

  # The key itself.
  #
  # @return [OpenSSL::PKey::RSA, OpenSSL::PKey::EC]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#60
  def key; end

  class << self
    # Create a KeyInfo from a single JWK, which may be given as either a
    # hash or an unparsed JSON string.
    #
    # @param jwk [Hash, String] The JWK specification.
    # @raise [KeySourceError] If the key could not be extracted from the
    #   JWK.
    # @return [KeyInfo]
    #
    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#78
    def from_jwk(jwk); end

    # Create an array of KeyInfo from a JWK Set, which may be given as
    # either a hash or an unparsed JSON string.
    #
    # @param jwk [Hash, String] The JWK Set specification.
    # @raise [KeySourceError] If a key could not be extracted from the
    #   JWK Set.
    # @return [Array<KeyInfo>]
    #
    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#102
    def from_jwk_set(jwk_set); end

    private

    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#111
    def ensure_json_parsed(input); end

    # @raise [KeySourceError]
    #
    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#146
    def extract_ec_key(jwk); end

    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#124
    def extract_rsa_key(jwk); end

    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#118
    def symbolize_keys(hash); end
  end
end

# Failed to obtain keys from the key source.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#24
class Google::Auth::IDTokens::KeySourceError < ::StandardError; end

# The URL for Google OAuth2 V3 public certs
#
# @return [String]
#
# source://googleauth//lib/googleauth/id_tokens.rb#102
Google::Auth::IDTokens::OAUTH2_V3_CERTS_URL = T.let(T.unsafe(nil), String)

# A list of issuers expected for Google OIDC-issued tokens.
#
# @return [Array<String>]
#
# source://googleauth//lib/googleauth/id_tokens.rb#88
Google::Auth::IDTokens::OIDC_ISSUERS = T.let(T.unsafe(nil), Array)

# Failed to verify a token because its signature did not match.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#39
class Google::Auth::IDTokens::SignatureError < ::Google::Auth::IDTokens::VerificationError; end

# A key source that contains a static set of keys.
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#173
class Google::Auth::IDTokens::StaticKeySource
  # Create a static key source with the given keys.
  #
  # @param keys [Array<KeyInfo>] The keys
  # @return [StaticKeySource] a new instance of StaticKeySource
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#179
  def initialize(keys); end

  # Return the current keys. Does not perform any refresh.
  #
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#188
  def current_keys; end

  # Return the current keys. Does not perform any refresh.
  #
  # @return [Array<KeyInfo>]
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#188
  def refresh_keys; end

  class << self
    # Create a static key source containing a single key parsed from a
    # single JWK, which may be given as either a hash or an unparsed
    # JSON string.
    #
    # @param jwk [Hash, String] The JWK specification.
    # @return [StaticKeySource]
    #
    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#200
    def from_jwk(jwk); end

    # Create a static key source containing multiple keys parsed from a
    # JWK Set, which may be given as either a hash or an unparsed JSON
    # string.
    #
    # @param jwk_set [Hash, String] The JWK Set specification.
    # @return [StaticKeySource]
    #
    # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#212
    def from_jwk_set(jwk_set); end
  end
end

# Failed to verify a token.
#
# source://googleauth//lib/googleauth/id_tokens/errors.rb#29
class Google::Auth::IDTokens::VerificationError < ::StandardError; end

# An object that can verify ID tokens.
#
# A verifier maintains a set of default settings, including the key
# source and fields to verify. However, individual verification calls can
# override any of these settings.
#
# source://googleauth//lib/googleauth/id_tokens/verifier.rb#29
class Google::Auth::IDTokens::Verifier
  # Create a verifier.
  #
  # @param key_source [key source] The default key source to use. All
  #   verification calls must have a key source, so if no default key
  #   source is provided here, then calls to {#verify} _must_ provide
  #   a key source.
  # @param aud [String, nil] The default audience (`aud`) check, or `nil`
  #   for no check.
  # @param azp [String, nil] The default authorized party (`azp`) check,
  #   or `nil` for no check.
  # @param iss [String, nil] The default issuer (`iss`) check, or `nil`
  #   for no check.
  # @return [Verifier] a new instance of Verifier
  #
  # source://googleauth//lib/googleauth/id_tokens/verifier.rb#44
  def initialize(key_source: T.unsafe(nil), aud: T.unsafe(nil), azp: T.unsafe(nil), iss: T.unsafe(nil)); end

  # Verify the given token.
  #
  # @param token [String] the ID token to verify.
  # @param key_source [key source] If given, override the key source.
  # @param aud [String, nil] If given, override the `aud` check.
  # @param azp [String, nil] If given, override the `azp` check.
  # @param iss [String, nil] If given, override the `iss` check.
  # @raise [KeySourceError] if the key source failed to obtain public keys
  # @raise [VerificationError] if the token verification failed.
  #   Additional data may be available in the error subclass and message.
  # @return [Hash] the decoded payload, if verification succeeded.
  #
  # source://googleauth//lib/googleauth/id_tokens/verifier.rb#68
  def verify(token, key_source: T.unsafe(nil), aud: T.unsafe(nil), azp: T.unsafe(nil), iss: T.unsafe(nil)); end

  private

  # source://googleauth//lib/googleauth/id_tokens/verifier.rb#91
  def decode_token(token, keys, aud, azp, iss); end

  # source://googleauth//lib/googleauth/id_tokens/verifier.rb#106
  def normalize_and_verify_payload(payload, aud, azp, iss); end
end

# A key source that downloads X509 certificates.
# Used by the legacy OAuth V1 public certs endpoint.
#
# source://googleauth//lib/googleauth/id_tokens/key_sources.rb#295
class Google::Auth::IDTokens::X509CertHttpKeySource < ::Google::Auth::IDTokens::HttpKeySource
  # Create a key source that downloads X509 certificates.
  #
  # @param uri [String, URI] The URI from which to download keys.
  # @param algorithm [String] The algorithm to use for signature
  #   verification. Defaults to "`RS256`".
  # @param retry_interval [Integer, nil] Override the retry interval in
  #   seconds. This is the minimum time between retries of failed key
  #   downloads.
  # @return [X509CertHttpKeySource] a new instance of X509CertHttpKeySource
  #
  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#306
  def initialize(uri, algorithm: T.unsafe(nil), retry_interval: T.unsafe(nil)); end

  protected

  # source://googleauth//lib/googleauth/id_tokens/key_sources.rb#313
  def interpret_json(data); end
end

# JsonKeyReader contains the behaviour used to read private key and
# client email fields from the service account
#
# source://googleauth//lib/googleauth/json_key_reader.rb#21
module Google::Auth::JsonKeyReader
  # source://googleauth//lib/googleauth/json_key_reader.rb#22
  def read_json_key(json_key_io); end
end

# source://googleauth//lib/googleauth/application_default.rb#22
Google::Auth::NOT_FOUND_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/compute_engine.rb#23
Google::Auth::NO_METADATA_SERVER_ERROR = T.let(T.unsafe(nil), String)

# Small utility for normalizing scopes into canonical form
#
# source://googleauth//lib/googleauth/scope_util.rb#22
module Google::Auth::ScopeUtil
  class << self
    # source://googleauth//lib/googleauth/scope_util.rb#34
    def as_array(scope); end

    # source://googleauth//lib/googleauth/scope_util.rb#29
    def normalize(scope); end
  end
end

# source://googleauth//lib/googleauth/scope_util.rb#23
Google::Auth::ScopeUtil::ALIASES = T.let(T.unsafe(nil), Hash)

# Authenticates requests using Google's Service Account credentials via an
# OAuth access token.
#
# This class allows authorizing requests for service accounts directly
# from credentials from a json key file downloaded from the developer
# console (via 'Generate new Json Key').
#
# cf [Application Default Credentials](https://cloud.google.com/docs/authentication/production)
#
# source://googleauth//lib/googleauth/service_account.rb#34
class Google::Auth::ServiceAccountCredentials < ::Signet::OAuth2::Client
  extend ::Google::Auth::CredentialsLoader
  extend ::Google::Auth::JsonKeyReader

  # @return [ServiceAccountCredentials] a new instance of ServiceAccountCredentials
  #
  # source://googleauth//lib/googleauth/service_account.rb#86
  def initialize(options = T.unsafe(nil)); end

  # Extends the base class to use a transient
  # ServiceAccountJwtHeaderCredentials for certain cases.
  #
  # source://googleauth//lib/googleauth/service_account.rb#95
  def apply!(a_hash, opts = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://googleauth//lib/googleauth/service_account.rb#41
  def enable_self_signed_jwt?; end

  # Returns the value of attribute project_id.
  #
  # source://googleauth//lib/googleauth/service_account.rb#38
  def project_id; end

  # Returns the value of attribute quota_project_id.
  #
  # source://googleauth//lib/googleauth/service_account.rb#39
  def quota_project_id; end

  private

  # source://googleauth//lib/googleauth/service_account.rb#108
  def apply_self_signed_jwt!(a_hash); end

  class << self
    # Creates a ServiceAccountCredentials.
    #
    # @param json_key_io [IO] an IO from which the JSON key can be read
    # @param scope [string|array|nil] the scope(s) to access
    # @raise [ArgumentError]
    #
    # source://googleauth//lib/googleauth/service_account.rb#49
    def make_creds(options = T.unsafe(nil)); end

    # Handles certain escape sequences that sometimes appear in input.
    # Specifically, interprets the "\n" sequence for newline, and removes
    # enclosing quotes.
    #
    # source://googleauth//lib/googleauth/service_account.rb#80
    def unescape(str); end
  end
end

# source://googleauth//lib/googleauth/service_account.rb#35
Google::Auth::ServiceAccountCredentials::TOKEN_CRED_URI = T.let(T.unsafe(nil), String)

# Authenticates requests using Google's Service Account credentials via
# JWT Header.
#
# This class allows authorizing requests for service accounts directly
# from credentials from a json key file downloaded from the developer
# console (via 'Generate new Json Key').  It is not part of any OAuth2
# flow, rather it creates a JWT and sends that as a credential.
#
# cf [Application Default Credentials](https://cloud.google.com/docs/authentication/production)
#
# source://googleauth//lib/googleauth/service_account.rb#131
class Google::Auth::ServiceAccountJwtHeaderCredentials
  extend ::Google::Auth::CredentialsLoader
  extend ::Google::Auth::JsonKeyReader

  # Initializes a ServiceAccountJwtHeaderCredentials.
  #
  # @param json_key_io [IO] an IO from which the JSON key can be read
  # @return [ServiceAccountJwtHeaderCredentials] a new instance of ServiceAccountJwtHeaderCredentials
  #
  # source://googleauth//lib/googleauth/service_account.rb#154
  def initialize(options = T.unsafe(nil)); end

  # Returns a clone of a_hash updated with the authoriation header
  #
  # source://googleauth//lib/googleauth/service_account.rb#183
  def apply(a_hash, opts = T.unsafe(nil)); end

  # Construct a jwt token if the JWT_AUD_URI key is present in the input
  # hash.
  #
  # The jwt token is used as the value of a 'Bearer '.
  #
  # source://googleauth//lib/googleauth/service_account.rb#174
  def apply!(a_hash, opts = T.unsafe(nil)); end

  # Returns the value of attribute project_id.
  #
  # source://googleauth//lib/googleauth/service_account.rb#139
  def project_id; end

  # Returns the value of attribute quota_project_id.
  #
  # source://googleauth//lib/googleauth/service_account.rb#140
  def quota_project_id; end

  # Returns a reference to the #apply method, suitable for passing as
  # a closure
  #
  # source://googleauth//lib/googleauth/service_account.rb#191
  def updater_proc; end

  protected

  # Creates a jwt uri token.
  #
  # source://googleauth//lib/googleauth/service_account.rb#198
  def new_jwt_token(jwt_aud_uri = T.unsafe(nil), options = T.unsafe(nil)); end

  class << self
    # Create a ServiceAccountJwtHeaderCredentials.
    #
    # @param json_key_io [IO] an IO from which the JSON key can be read
    # @param scope [string|array|nil] the scope(s) to access
    #
    # source://googleauth//lib/googleauth/service_account.rb#146
    def make_creds(options = T.unsafe(nil)); end
  end
end

# source://googleauth//lib/googleauth/service_account.rb#133
Google::Auth::ServiceAccountJwtHeaderCredentials::AUTH_METADATA_KEY = T.let(T.unsafe(nil), Symbol)

# source://googleauth//lib/googleauth/service_account.rb#136
Google::Auth::ServiceAccountJwtHeaderCredentials::EXPIRY = T.let(T.unsafe(nil), Integer)

# source://googleauth//lib/googleauth/service_account.rb#132
Google::Auth::ServiceAccountJwtHeaderCredentials::JWT_AUD_URI_KEY = T.let(T.unsafe(nil), Symbol)

# source://googleauth//lib/googleauth/service_account.rb#135
Google::Auth::ServiceAccountJwtHeaderCredentials::SIGNING_ALGORITHM = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/service_account.rb#134
Google::Auth::ServiceAccountJwtHeaderCredentials::TOKEN_CRED_URI = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/compute_engine.rb#29
Google::Auth::UNEXPECTED_ERROR_SUFFIX = T.let(T.unsafe(nil), String)

# Handles an interactive 3-Legged-OAuth2 (3LO) user consent authorization.
#
# Example usage for a simple command line app:
#
#     credentials = authorizer.get_credentials(user_id)
#     if credentials.nil?
#       url = authorizer.get_authorization_url(
#         base_url: OOB_URI)
#       puts "Open the following URL in the browser and enter the " +
#            "resulting code after authorization"
#       puts url
#       code = gets
#       credentials = authorizer.get_and_store_credentials_from_code(
#         user_id: user_id, code: code, base_url: OOB_URI)
#     end
#     # Credentials ready to use, call APIs
#     ...
#
# source://googleauth//lib/googleauth/user_authorizer.rb#39
class Google::Auth::UserAuthorizer
  # Initialize the authorizer
  #
  # @param client_id [Google::Auth::ClientID] Configured ID & secret for this application
  # @param scope [String, Array<String>] Authorization scope to request
  # @param token_store [Google::Auth::Stores::TokenStore] Backing storage for persisting user credentials
  # @param callback_uri [String] URL (either absolute or relative) of the auth callback.
  #   Defaults to '/oauth2callback'
  # @raise [NIL_CLIENT_ID_ERROR]
  # @return [UserAuthorizer] a new instance of UserAuthorizer
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#60
  def initialize(client_id, scope, token_store, callback_uri = T.unsafe(nil)); end

  # Exchanges an authorization code returned in the oauth callback.
  # Additionally, stores the resulting credentials in the token store if
  # the exchange is successful.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param code [String] The authorization code from the OAuth callback
  # @param scope [String, Array<String>] Authorization scope requested. Overrides the instance
  #   scopes if not nil.
  # @param base_url [String] Absolute URL to resolve the configured callback uri against.
  #   Required if the configured
  #   callback uri is a relative.
  # @return [Google::Auth::UserRefreshCredentials] Credentials if exchange is successful
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#182
  def get_and_store_credentials_from_code(options = T.unsafe(nil)); end

  # Build the URL for requesting authorization.
  #
  # @param login_hint [String] Login hint if need to authorize a specific account. Should be a
  #   user's email address or unique profile ID.
  # @param state [String] Opaque state value to be returned to the oauth callback.
  # @param base_url [String] Absolute URL to resolve the configured callback uri against. Required
  #   if the configured callback uri is a relative.
  # @param scope [String, Array<String>] Authorization scope to request. Overrides the instance scopes if not
  #   nil.
  # @return [String] Authorization url
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#85
  def get_authorization_url(options = T.unsafe(nil)); end

  # Fetch stored credentials for the user.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param scope [Array<String>, String] If specified, only returns credentials that have all
  #   the requested scopes
  # @return [Google::Auth::UserRefreshCredentials] Stored credentials, nil if none present
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#111
  def get_credentials(user_id, scope = T.unsafe(nil)); end

  # Exchanges an authorization code returned in the oauth callback
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param code [String] The authorization code from the OAuth callback
  # @param scope [String, Array<String>] Authorization scope requested. Overrides the instance
  #   scopes if not nil.
  # @param base_url [String] Absolute URL to resolve the configured callback uri against.
  #   Required if the configured
  #   callback uri is a relative.
  # @return [Google::Auth::UserRefreshCredentials] Credentials if exchange is successful
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#149
  def get_credentials_from_code(options = T.unsafe(nil)); end

  # Revokes a user's credentials. This both revokes the actual
  # grant as well as removes the token from the token store.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#192
  def revoke_authorization(user_id); end

  # Store credentials for a user. Generally not required to be
  # called directly, but may be used to migrate tokens from one
  # store to another.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param credentials [Google::Auth::UserRefreshCredentials] Credentials to store.
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#212
  def store_credentials(user_id, credentials); end

  private

  # Begin watching a credential for refreshes so the access token can be
  # saved.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param credentials [Google::Auth::UserRefreshCredentials] Credentials to store.
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#245
  def monitor_credentials(user_id, credentials); end

  # Resolve the redirect uri against a base.
  #
  # @param base_url [String] Absolute URL to resolve the callback against if necessary.
  # @return [String] Redirect URI
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#258
  def redirect_uri_for(base_url); end

  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @private Fetch stored token with given user_id
  # @raise [NIL_USER_ID_ERROR]
  # @return [String] The saved token from @token_store
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#231
  def stored_token(user_id); end

  # Check if URI is Google's postmessage flow (not a valid redirect_uri by spec, but allowed)
  #
  # @return [Boolean]
  #
  # source://googleauth//lib/googleauth/user_authorizer.rb#265
  def uri_is_postmessage?(uri); end
end

# source://googleauth//lib/googleauth/user_authorizer.rb#40
Google::Auth::UserAuthorizer::MISMATCHED_CLIENT_ID_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_authorizer.rb#46
Google::Auth::UserAuthorizer::MISSING_ABSOLUTE_URL_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_authorizer.rb#42
Google::Auth::UserAuthorizer::NIL_CLIENT_ID_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_authorizer.rb#43
Google::Auth::UserAuthorizer::NIL_SCOPE_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_authorizer.rb#45
Google::Auth::UserAuthorizer::NIL_TOKEN_STORE_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_authorizer.rb#44
Google::Auth::UserAuthorizer::NIL_USER_ID_ERROR = T.let(T.unsafe(nil), String)

# Authenticates requests using User Refresh credentials.
#
# This class allows authorizing requests from user refresh tokens.
#
# This the end of the result of a 3LO flow.  E.g, the end result of
# 'gcloud auth login' saves a file with these contents in well known
# location
#
# cf [Application Default Credentials](https://cloud.google.com/docs/authentication/production)
#
# source://googleauth//lib/googleauth/user_refresh.rb#33
class Google::Auth::UserRefreshCredentials < ::Signet::OAuth2::Client
  extend ::Google::Auth::CredentialsLoader

  # @return [UserRefreshCredentials] a new instance of UserRefreshCredentials
  #
  # source://googleauth//lib/googleauth/user_refresh.rb#76
  def initialize(options = T.unsafe(nil)); end

  # Verifies that a credential grants the requested scope
  #
  # @param required_scope [Array<String>, String] Scope to verify
  # @return [Boolean] True if scope is granted
  #
  # source://googleauth//lib/googleauth/user_refresh.rb#110
  def includes_scope?(required_scope); end

  # Returns the value of attribute project_id.
  #
  # source://googleauth//lib/googleauth/user_refresh.rb#38
  def project_id; end

  # Returns the value of attribute quota_project_id.
  #
  # source://googleauth//lib/googleauth/user_refresh.rb#39
  def quota_project_id; end

  # Revokes the credential
  #
  # source://googleauth//lib/googleauth/user_refresh.rb#87
  def revoke!(options = T.unsafe(nil)); end

  class << self
    # Create a UserRefreshCredentials.
    #
    # @param json_key_io [IO] an IO from which the JSON key can be read
    # @param scope [string|array|nil] the scope(s) to access
    #
    # source://googleauth//lib/googleauth/user_refresh.rb#45
    def make_creds(options = T.unsafe(nil)); end

    # Reads the client_id, client_secret and refresh_token fields from the
    # JSON key.
    #
    # source://googleauth//lib/googleauth/user_refresh.rb#67
    def read_json_key(json_key_io); end
  end
end

# source://googleauth//lib/googleauth/user_refresh.rb#35
Google::Auth::UserRefreshCredentials::AUTHORIZATION_URI = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_refresh.rb#36
Google::Auth::UserRefreshCredentials::REVOKE_TOKEN_URI = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/user_refresh.rb#34
Google::Auth::UserRefreshCredentials::TOKEN_CRED_URI = T.let(T.unsafe(nil), String)

# Varation on {Google::Auth::UserAuthorizer} adapted for Rack based
# web applications.
#
# Example usage:
#
#     get('/') do
#       user_id = request.session['user_email']
#       credentials = authorizer.get_credentials(user_id, request)
#       if credentials.nil?
#         redirect authorizer.get_authorization_url(user_id: user_id,
#                                                   request: request)
#       end
#       # Credentials are valid, can call APIs
#       ...
#    end
#
#    get('/oauth2callback') do
#      url = Google::Auth::WebUserAuthorizer.handle_auth_callback_deferred(
#        request)
#      redirect url
#    end
#
# Instead of implementing the callback directly, applications are
# encouraged to use {Google::Auth::WebUserAuthorizer::CallbackApp} instead.
#
# @note Requires sessions are enabled
# @see CallbackApp
#
# source://googleauth//lib/googleauth/web_user_authorizer.rb#50
class Google::Auth::WebUserAuthorizer < ::Google::Auth::UserAuthorizer
  # Initialize the authorizer
  #
  # @param client_id [Google::Auth::ClientID] Configured ID & secret for this application
  # @param scope [String, Array<String>] Authorization scope to request
  # @param token_store [Google::Auth::Stores::TokenStore] Backing storage for persisting user credentials
  # @param callback_uri [String] URL (either absolute or relative) of the auth callback. Defaults
  #   to '/oauth2callback'
  # @return [WebUserAuthorizer] a new instance of WebUserAuthorizer
  #
  # source://googleauth//lib/googleauth/web_user_authorizer.rb#99
  def initialize(client_id, scope, token_store, callback_uri = T.unsafe(nil)); end

  # Build the URL for requesting authorization.
  #
  # @param login_hint [String] Login hint if need to authorize a specific account. Should be a
  #   user's email address or unique profile ID.
  # @param request [Rack::Request] Current request
  # @param redirect_to [String] Optional URL to proceed to after authorization complete. Defaults to
  #   the current URL.
  # @param scope [String, Array<String>] Authorization scope to request. Overrides the instance scopes if
  #   not nil.
  # @param state [Hash] Optional key-values to be returned to the oauth callback.
  # @raise [NIL_REQUEST_ERROR]
  # @return [String] Authorization url
  #
  # source://googleauth//lib/googleauth/web_user_authorizer.rb#143
  def get_authorization_url(options = T.unsafe(nil)); end

  # Fetch stored credentials for the user from the given request session.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param request [Rack::Request] Current request. Optional. If omitted, this will attempt to fall back
  #   on the base class behavior of reading from the token store.
  # @param scope [Array<String>, String] If specified, only returns credentials that have all the \
  #   requested scopes
  # @raise [Signet::AuthorizationError] May raise an error if an authorization code is present in the session
  #   and exchange of the code fails
  # @return [Google::Auth::UserRefreshCredentials] Stored credentials, nil if none present
  #
  # source://googleauth//lib/googleauth/web_user_authorizer.rb#176
  def get_credentials(user_id, request = T.unsafe(nil), scope = T.unsafe(nil)); end

  # Handle the result of the oauth callback. Exchanges the authorization
  # code from the request and persists to storage.
  #
  # @param user_id [String] Unique ID of the user for loading/storing credentials.
  # @param request [Rack::Request] Current request
  # @return [Google::Auth::UserRefreshCredentials, String] credentials & next URL to redirect to
  #
  # source://googleauth//lib/googleauth/web_user_authorizer.rb#112
  def handle_auth_callback(user_id, request); end

  class << self
    # Returns the value of attribute default.
    #
    # source://googleauth//lib/googleauth/web_user_authorizer.rb#68
    def default; end

    # Sets the attribute default
    #
    # @param value the value to set the attribute default to.
    #
    # source://googleauth//lib/googleauth/web_user_authorizer.rb#68
    def default=(_arg0); end

    # source://googleauth//lib/googleauth/web_user_authorizer.rb#194
    def extract_callback_state(request); end

    # Handle the result of the oauth callback. This version defers the
    # exchange of the code by temporarily stashing the results in the user's
    # session. This allows apps to use the generic
    # {Google::Auth::WebUserAuthorizer::CallbackApp} handler for the callback
    # without any additional customization.
    #
    # Apps that wish to handle the callback directly should use
    # {#handle_auth_callback} instead.
    #
    # @param request [Rack::Request] Current request
    #
    # source://googleauth//lib/googleauth/web_user_authorizer.rb#82
    def handle_auth_callback_deferred(request); end

    # Verifies the results of an authorization callback
    #
    # @option state
    # @option state
    # @param state [Hash] Callback state
    # @param request [Rack::Request] Current request
    # @raise [Signet::AuthorizationError]
    #
    # source://googleauth//lib/googleauth/web_user_authorizer.rb#216
    def validate_callback_state(state, request); end
  end
end

# source://googleauth//lib/googleauth/web_user_authorizer.rb#63
Google::Auth::WebUserAuthorizer::AUTHORIZATION_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#52
Google::Auth::WebUserAuthorizer::AUTH_CODE_KEY = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#55
Google::Auth::WebUserAuthorizer::CALLBACK_STATE_KEY = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#56
Google::Auth::WebUserAuthorizer::CURRENT_URI_KEY = T.let(T.unsafe(nil), String)

# Small Rack app which acts as the default callback handler for the app.
#
# To configure in Rails, add to routes.rb:
#
#     match '/oauth2callback',
#           to: Google::Auth::WebUserAuthorizer::CallbackApp,
#           via: :all
#
# With Rackup, add to config.ru:
#
#     map '/oauth2callback' do
#       run Google::Auth::WebUserAuthorizer::CallbackApp
#     end
#
# Or in a classic Sinatra app:
#
#     get('/oauth2callback') do
#       Google::Auth::WebUserAuthorizer::CallbackApp.call(env)
#     end
#
# @see Google::Auth::WebUserAuthorizer
#
# source://googleauth//lib/googleauth/web_user_authorizer.rb#247
class Google::Auth::WebUserAuthorizer::CallbackApp
  # source://googleauth//lib/googleauth/web_user_authorizer.rb#274
  def call(env); end

  class << self
    # Handle a rack request. Simply stores the results the authorization
    # in the session temporarily and redirects back to to the previously
    # saved redirect URL. Credentials can be later retrieved by calling.
    # {Google::Auth::Web::WebUserAuthorizer#get_credentials}
    #
    # See {Google::Auth::Web::WebUserAuthorizer#get_authorization_uri}
    # for how to initiate authorization requests.
    #
    # @param env [Hash] Rack environment
    # @return [Array] HTTP response
    #
    # source://googleauth//lib/googleauth/web_user_authorizer.rb#264
    def call(env); end
  end
end

# source://googleauth//lib/googleauth/web_user_authorizer.rb#250
Google::Auth::WebUserAuthorizer::CallbackApp::ERROR_STATUS = T.let(T.unsafe(nil), Integer)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#248
Google::Auth::WebUserAuthorizer::CallbackApp::LOCATION_HEADER = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#249
Google::Auth::WebUserAuthorizer::CallbackApp::REDIR_STATUS = T.let(T.unsafe(nil), Integer)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#53
Google::Auth::WebUserAuthorizer::ERROR_CODE_KEY = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#64
Google::Auth::WebUserAuthorizer::INVALID_STATE_TOKEN_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#62
Google::Auth::WebUserAuthorizer::MISSING_AUTH_CODE_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#60
Google::Auth::WebUserAuthorizer::NIL_REQUEST_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#61
Google::Auth::WebUserAuthorizer::NIL_SESSION_ERROR = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#58
Google::Auth::WebUserAuthorizer::SCOPE_KEY = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#54
Google::Auth::WebUserAuthorizer::SESSION_ID_KEY = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#51
Google::Auth::WebUserAuthorizer::STATE_PARAM = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/web_user_authorizer.rb#57
Google::Auth::WebUserAuthorizer::XSRF_KEY = T.let(T.unsafe(nil), String)

# source://googleauth//lib/googleauth/signet.rb#17
module Signet
  class << self
    # source://signet/0.17.0/lib/signet.rb#18
    def parse_auth_param_list(auth_param_string); end
  end
end

# OAuth2 supports OAuth2 authentication.
#
# source://googleauth//lib/googleauth/signet.rb#19
module Signet::OAuth2
  class << self
    # source://signet/0.17.0/lib/signet/oauth_2.rb#137
    def generate_authorization_uri(authorization_uri, parameters = T.unsafe(nil)); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#98
    def generate_basic_authorization_header(client_id, client_password); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#117
    def generate_bearer_authorization_header(access_token, auth_params = T.unsafe(nil)); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#26
    def parse_authorization_header(field_value); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#53
    def parse_basic_credentials(credential_string); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#59
    def parse_bearer_credentials(credential_string); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#75
    def parse_credentials(body, content_type); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#71
    def parse_oauth_challenge(challenge_string); end

    # source://signet/0.17.0/lib/signet/oauth_2.rb#41
    def parse_www_authenticate_header(field_value); end
  end
end

# source://googleauth//lib/googleauth/signet.rb#20
Signet::OAuth2::AUTH_METADATA_KEY = T.let(T.unsafe(nil), Symbol)

# Signet::OAuth2::Client creates an OAuth2 client
#
# This reopens Client to add #apply and #apply! methods which update a
# hash with the fetched authentication token.
#
# source://googleauth//lib/googleauth/signet.rb#25
class Signet::OAuth2::Client
  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#95
  def initialize(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#710
  def access_token; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#719
  def access_token=(new_access_token); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#337
  def access_type; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#346
  def access_type=(new_access_type); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#671
  def additional_parameters; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#680
  def additional_parameters=(new_additional_parameters); end

  # Returns a clone of a_hash updated with the authentication token
  #
  # source://googleauth//lib/googleauth/signet.rb#51
  def apply(a_hash, opts = T.unsafe(nil)); end

  # Updates a_hash updated with the authentication token
  #
  # source://googleauth//lib/googleauth/signet.rb#43
  def apply!(a_hash, opts = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#556
  def audience; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#566
  def audience=(new_audience); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#266
  def authorization_uri(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#302
  def authorization_uri=(new_authorization_uri); end

  # source://googleauth//lib/googleauth/signet.rb#88
  def build_default_connection; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#851
  def clear_credentials!; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#354
  def client_id; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#363
  def client_id=(new_client_id); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#371
  def client_secret; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#380
  def client_secret=(new_client_secret); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#457
  def code; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#467
  def code=(new_code); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#325
  def coerce_uri(incoming_uri); end

  # source://googleauth//lib/googleauth/signet.rb#26
  def configure_connection(options); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#748
  def decoded_id_token(public_key = T.unsafe(nil), options = T.unsafe(nil), &keyfinder); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#832
  def expired?; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#812
  def expires_at; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#822
  def expires_at=(new_expires_at); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#765
  def expires_in; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#780
  def expires_in=(new_expires_in); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#845
  def expires_within?(sec); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#603
  def expiry; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#613
  def expiry=(new_expiry); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#648
  def extension_parameters; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#658
  def extension_parameters=(new_extension_parameters); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#988
  def fetch_access_token(options = T.unsafe(nil)); end

  # source://googleauth//lib/googleauth/signet.rb#69
  def fetch_access_token!(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1153
  def fetch_protected_resource(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#953
  def generate_access_token_request(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1077
  def generate_authenticated_request(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#869
  def grant_type; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#883
  def grant_type=(new_grant_type); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#727
  def id_token; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#736
  def id_token=(new_id_token); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#794
  def issued_at; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#803
  def issued_at=(new_issued_at); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#537
  def issuer; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#547
  def issuer=(new_issuer); end

  # Whether the id_token or access_token is missing or about to expire.
  #
  # @return [Boolean]
  #
  # source://googleauth//lib/googleauth/signet.rb#38
  def needs_access_token?; end

  # source://googleauth//lib/googleauth/signet.rb#81
  def notify_refresh_listeners; end

  # source://googleauth//lib/googleauth/signet.rb#63
  def on_refresh(&block); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1038
  def orig_fetch_access_token!(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#518
  def password; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#528
  def password=(new_password); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#575
  def person; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#585
  def person=(new_person); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#575
  def principal; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#585
  def principal=(new_person); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#475
  def redirect_uri; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#484
  def redirect_uri=(new_redirect_uri); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1053
  def refresh!(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#693
  def refresh_token; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#702
  def refresh_token=(new_refresh_token); end

  # source://googleauth//lib/googleauth/signet.rb#98
  def retry_with_error(max_retry_count = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#389
  def scope; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#400
  def scope=(new_scope); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#639
  def signing_algorithm; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#622
  def signing_key; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#632
  def signing_key=(new_key); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#439
  def state; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#448
  def state=(new_state); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#596
  def sub; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#596
  def sub=(_arg0); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#423
  def target_audience; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#431
  def target_audience=(new_target_audience); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#917
  def to_json(*_args); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#893
  def to_jwt(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#310
  def token_credential_uri; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#319
  def token_credential_uri=(new_token_credential_uri); end

  # The token type as symbol, either :id_token or :access_token
  #
  # source://googleauth//lib/googleauth/signet.rb#33
  def token_type; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#180
  def update!(options = T.unsafe(nil)); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#236
  def update_token!(options = T.unsafe(nil)); end

  # Returns a reference to the #apply method, suitable for passing as
  # a closure
  #
  # source://googleauth//lib/googleauth/signet.rb#59
  def updater_proc; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#499
  def username; end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#509
  def username=(new_username); end

  private

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1196
  def deep_hash_normalize(old_hash); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1202
  def normalize_timestamp(time); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1188
  def recursive_hash_normalize_keys(val); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1219
  def set_relative_expires_at(issued_at, expires_in); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1183
  def uri_is_oob?(uri); end

  # source://signet/0.17.0/lib/signet/oauth_2/client.rb#1176
  def uri_is_postmessage?(uri); end
end
