# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rgeo-geojson` gem.
# Please instead update this file by running `bin/tapioca gem rgeo-geojson`.


# source://rgeo-geojson//lib/rgeo/geo_json/version.rb#3
module RGeo; end

# source://rgeo-geojson//lib/rgeo/geo_json/version.rb#4
module RGeo::GeoJSON
  class << self
    # Creates and returns a coder object of type RGeo::GeoJSON::Coder
    # that encapsulates encoding and decoding settings (principally the
    # RGeo::Feature::Factory and the RGeo::GeoJSON::EntityFactory to be
    # used).
    #
    # The geo factory is a required argument. Other options include:
    #
    # [<tt>:geo_factory</tt>]
    #   Specifies the geo factory to use to create geometry objects.
    #   Defaults to the preferred cartesian factory.
    # [<tt>:entity_factory</tt>]
    #   Specifies an entity factory, which lets you override the types
    #   of GeoJSON entities that are created. It defaults to the default
    #   RGeo::GeoJSON::EntityFactory, which generates objects of type
    #   RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
    #   See RGeo::GeoJSON::EntityFactory for more information.
    #
    # source://rgeo-geojson//lib/rgeo/geo_json/interface.rb#56
    def coder(opts = T.unsafe(nil)); end

    # High-level convenience routine for decoding an object from GeoJSON.
    # The input may be a JSON hash, a String, or an IO object from which
    # to read the JSON string.
    #
    # Options include:
    #
    # [<tt>:geo_factory</tt>]
    #   Specifies the geo factory to use to create geometry objects.
    #   Defaults to the preferred cartesian factory.
    # [<tt>:entity_factory</tt>]
    #   Specifies an entity factory, which lets you override the types
    #   of GeoJSON entities that are created. It defaults to the default
    #   RGeo::GeoJSON::EntityFactory, which generates objects of type
    #   RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
    #   See RGeo::GeoJSON::EntityFactory for more information.
    #
    # source://rgeo-geojson//lib/rgeo/geo_json/interface.rb#36
    def decode(input_, opts = T.unsafe(nil)); end

    # High-level convenience routine for encoding an object as GeoJSON.
    # Pass the object, which may one of the geometry objects specified
    # in RGeo::Feature, or an appropriate GeoJSON wrapper entity such
    # as RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
    #
    # The only option supported is <tt>:entity_factory</tt>, which lets
    # you override the types of GeoJSON entities supported. See
    # RGeo::GeoJSON::EntityFactory for more information. By default,
    # encode supports objects of type RGeo::GeoJSON::Feature and
    # RGeo::GeoJSON::FeatureCollection.
    #
    # source://rgeo-geojson//lib/rgeo/geo_json/interface.rb#17
    def encode(object, opts = T.unsafe(nil)); end
  end
end

# This object encapsulates encoding and decoding settings (principally
# the RGeo::Feature::Factory and the RGeo::GeoJSON::EntityFactory to
# be used) so that you can encode and decode without specifying those
# settings every time.
#
# source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#10
class RGeo::GeoJSON::Coder
  # Create a new coder settings object. The geo factory is passed as
  # a required argument.
  #
  # Options include:
  #
  # [<tt>:geo_factory</tt>]
  #   Specifies the geo factory to use to create geometry objects.
  #   Defaults to the preferred cartesian factory.
  # [<tt>:entity_factory</tt>]
  #   Specifies an entity factory, which lets you override the types
  #   of GeoJSON entities that are created. It defaults to the default
  #   RGeo::GeoJSON::EntityFactory, which generates objects of type
  #   RGeo::GeoJSON::Feature or RGeo::GeoJSON::FeatureCollection.
  #   See RGeo::GeoJSON::EntityFactory for more information.
  #
  # @return [Coder] a new instance of Coder
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#25
  def initialize(opts = T.unsafe(nil)); end

  # Decode an object from GeoJSON. The input may be a JSON hash, a
  # String, or an IO object from which to read the JSON string.
  # If an error occurs, nil is returned.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#64
  def decode(input); end

  # Encode the given object as GeoJSON. The object may be one of the
  # geometry objects specified in RGeo::Feature, or an appropriate
  # GeoJSON wrapper entity supported by this coder's entity factory.
  #
  # This method returns a JSON object (i.e. a hash). In order to
  # generate a string suitable for transmitting to a service, you
  # will need to JSON-encode it. This is usually accomplished by
  # calling <tt>to_json</tt> on the hash object, if you have the
  # appropriate JSON library installed.
  #
  # Returns nil if nil is passed in as the object.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#45
  def encode(object); end

  # Returns the RGeo::GeoJSON::EntityFactory used to generate GeoJSON
  # wrapper entities.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#98
  def entity_factory; end

  # Returns the RGeo::Feature::Factory used to generate geometry objects.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#93
  def geo_factory; end

  private

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#155
  def decode_feature(input); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#164
  def decode_geometry(input); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#185
  def decode_geometry_collection(input); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#201
  def decode_line_string_coords(line_coords); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#241
  def decode_multi_line_string_coords(multi_line_coords); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#231
  def decode_multi_point_coords(multi_point_coords); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#251
  def decode_multi_polygon_coords(multi_polygon_coords); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#196
  def decode_point_coords(point_coords); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#211
  def decode_polygon_coords(poly_coords); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#102
  def encode_feature(object); end

  # source://rgeo-geojson//lib/rgeo/geo_json/coder.rb#113
  def encode_geometry(object); end
end

# This is the default entity factory. It creates objects of type
# RGeo::GeoJSON::Feature and RGeo::GeoJSON::FeatureCollection.
# You may create your own entity factory by duck-typing this class.
#
# source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#163
class RGeo::GeoJSON::EntityFactory
  # Create and return a new feature, given geometry, ID, and
  # properties hash. Note that, per the GeoJSON spec, geometry and/or
  # properties may be nil.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#168
  def feature(geometry, id = T.unsafe(nil), properties = T.unsafe(nil)); end

  # Create and return a new feature collection, given an enumerable
  # of feature objects.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#175
  def feature_collection(features = T.unsafe(nil)); end

  # Returns the geometry associated with the given feature.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#202
  def get_feature_geometry(object); end

  # Returns the ID of the given feature, or nil for no ID.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#208
  def get_feature_id(object); end

  # Returns the properties of the given feature as a hash. Editing
  # this hash does not change the state of the feature.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#215
  def get_feature_properties(object); end

  # Returns true if the given object is a feature created by this
  # entity factory.
  #
  # @return [Boolean]
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#182
  def is_feature?(object); end

  # Returns true if the given object is a feature collection created
  # by this entity factory.
  #
  # @return [Boolean]
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#189
  def is_feature_collection?(object); end

  # Run Enumerable#map on the features contained in the given feature
  # collection.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#196
  def map_feature_collection(object, &block); end

  class << self
    # Return the singleton instance of EntityFactory.
    #
    # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#221
    def instance; end
  end
end

# This is a GeoJSON wrapper entity that corresponds to the GeoJSON
# "Feature" type. It is an immutable type.
#
# This is the default implementation that is generated by
# RGeo::GeoJSON::EntityFactory. You may replace this implementation
# by writing your own entity factory. Note that an alternate Feature
# implementation need not subclass or even duck-type this class.
# the entity factory mediates all interaction between the GeoJSON
# engine and features.
#
# source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#15
class RGeo::GeoJSON::Feature
  # Create a feature wrapping the given geometry, with the given ID
  # and properties.
  #
  # @return [Feature] a new instance of Feature
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#19
  def initialize(geometry, id = T.unsafe(nil), properties = T.unsafe(nil)); end

  # Two features are equal if their geometries, IDs, and properties
  # are all equal.
  # This method uses the == operator to test geometry equality, which
  # may behave differently than the eql? method.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#54
  def ==(other); end

  # Gets the value of the given named property.
  # Returns nil if the given property is not found.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#77
  def [](key); end

  # Two features are equal if their geometries, IDs, and properties
  # are all equal.
  # This method uses the eql? method to test geometry equality, which
  # may behave differently than the == operator.
  #
  # @return [Boolean]
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#45
  def eql?(other); end

  # Returns the ID for this feature, which may be nil.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#64
  def feature_id; end

  # Returns the geometry contained in this feature, which may be nil.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#60
  def geometry; end

  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#36
  def hash; end

  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#28
  def inspect; end

  # Gets an array of the known property keys in this feature.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#84
  def keys; end

  # Returns a copy of the properties for this feature.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#70
  def properties; end

  # Gets the value of the given named property.
  # Returns nil if the given property is not found.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#77
  def property(key); end

  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#32
  def to_s; end
end

# This is a GeoJSON wrapper entity that corresponds to the GeoJSON
# "FeatureCollection" type. It is an immutable type.
#
# This is the default implementation that is generated by
# RGeo::GeoJSON::EntityFactory. You may replace this implementation
# by writing your own entity factory. Note that an alternate
# FeatureCollection implementation need not subclass or even
# duck-type this class. The entity factory mediates all interaction
# between the GeoJSON engine and feature collections.
#
# source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#99
class RGeo::GeoJSON::FeatureCollection
  include ::Enumerable

  # Create a new FeatureCollection with the given features, which must
  # be provided as an Enumerable.
  #
  # @return [FeatureCollection] a new instance of FeatureCollection
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#105
  def initialize(features = T.unsafe(nil)); end

  # Two feature collections are equal if they contain the same
  # features in the same order.
  # This methods uses the == operator to test geometry equality, which
  # may behave differently than the eql? method.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#136
  def ==(other); end

  # Access a feature by index.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#154
  def [](index); end

  # Iterates or returns an iterator for the features.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#142
  def each(&block); end

  # Two feature collections are equal if they contain the same
  # features in the same order.
  # This methods uses the eql? method to test geometry equality, which
  # may behave differently than the == operator.
  #
  # @return [Boolean]
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#127
  def eql?(other); end

  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#118
  def hash; end

  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#110
  def inspect; end

  # Returns the number of features contained in this collection.
  #
  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#148
  def size; end

  # source://rgeo-geojson//lib/rgeo/geo_json/entities.rb#114
  def to_s; end
end

# source://rgeo-geojson//lib/rgeo/geo_json/version.rb#5
RGeo::GeoJSON::VERSION = T.let(T.unsafe(nil), String)
