---
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - '**/vendor/**/*'
  - '**/app/components/**/*'
  - '**/app/views/accounts/**/*'
  - '**/app/views/app_configs/**/*'
  - '**/app/views/app_variants/**/*'
  - '**/app/views/approval_assignment_mailer/**/*'
  - '**/app/views/approval_items/**/*'
  - '**/app/views/apps/**/*'
  - '**/app/views/authentication/**/*'
  - '**/app/views/beta_releases/**/*'
  - '**/app/views/config/**/*'
  - '**/app/views/devise/**/*'
  - '**/app/views/errors/**/*'
  - '**/app/views/integrations/**/*'
  - '**/app/views/internal_releases/**/*'
  - '**/app/views/invitation_mailer/**/*'
  - '**/app/views/jira_integration/**/*'
  - '**/app/views/layouts/**/*'
  - '**/app/views/notification_settings/**/*'
  - '**/app/views/notifiers/**/*'
  - '**/app/views/pre_prod_releases/**/*'
  - '**/app/views/production_releases/**/*'
  - '**/app/views/release_indices/**/*'
  - '**/app/views/release_list/**/*'
  - '**/app/views/release_metadata/**/*'
  - '**/app/views/releases/**/*'
  - '**/app/views/scheduled_release/**/*'
  - '**/app/views/shared/**/*'
  - '**/app/views/store_rollouts/**/*'
  - '**/app/views/store_submissions/**/*'
  - '**/app/views/test_mailer/**/*'
  - '**/app/views/trains/**/*'
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
