# This override file configures the worktree to run independently with its own
# postgres and redis containers on unique ports.
#
# Ports are dynamically assigned based on worktree name hash via environment
# variables set by the Justfile.

services:
  # Configure web with dynamic port
  web:
    ports: !override
      - '${WEB_PORT:-3001}:3000'  # Dynamic port based on worktree name
    environment:
      PORT_NUM: ${WEB_PORT:-3001}  # Dynamic port for URL generation
      # Ngrok URLs - will use ngrok if running, otherwise localhost
      # To use ngrok, add NGROK_AUTHTOKEN to .env.development and start ngrok manually
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
      ngrok:
        condition: service_started
        required: false  # Make ngrok optional - won't block if it fails
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "-H", "X-Monitor-Allowed: 1", "https://localhost:3000/up"]
      interval: 60s
      timeout: 1s
      retries: 2
      start_period: 3s

  worker:
    environment:
      PORT_NUM: ${WEB_PORT:-3001}  # Dynamic port for URL generation
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
      ngrok:
        condition: service_started
        required: false

  # Configure ngrok for worktree on different port
  # Ngrok will start automatically if NGROK_AUTHTOKEN is set in .env.development
  # Otherwise it will fail but won't block other services (restart: "no")
  # Tunnels to the worktree's exposed web port (dynamically assigned)
  ngrok:
    command: ["http", "https://host.docker.internal:${WEB_PORT:-3001}", "--log=stdout", "--host-header=rewrite"]
    ports: !reset
      - '${NGROK_PORT:-4041}:4040'  # Dynamic port based on worktree name
    restart: "no"  # Don't restart on failure (e.g., missing authtoken)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: bash -c "</dev/tcp/ngrok/4040"
      interval: 60s
      timeout: 1s
      retries: 2
      start_period: 3s

  # Give each worktree its own postgres and redis with unique ports
  # Data is stored in named volumes prefixed with the project name (worktree directory name)
  postgres:
    ports: !override
      - '${POSTGRES_PORT:-5442}:5432'  # Dynamic postgres port

  redis:
    ports: !override
      - '${REDIS_PORT:-6389}:6379'  # Dynamic redis port
