# This override file makes the worktree use the same postgres and redis
# containers from the main tramline repository instead of creating new ones.
#
# Make sure the main tramline repository's postgres and redis containers are running
# before starting services in this worktree.
#
# Ports are dynamically assigned based on worktree name hash via WEB_PORT and NGROK_PORT.
services:
  web:
    ports: !override
      - '${WEB_PORT:-3001}:3000'
    environment:
      PORT_NUM: ${WEB_PORT:-3001}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    environment:
      PORT_NUM: ${WEB_PORT:-3001}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  setup:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: {}

  spec:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  css:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      web:
        condition: service_healthy

  # Override postgres and redis to do nothing (use main repo's containers)
  postgres:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    restart: "no"
    ports: !reset []
    volumes: !reset []
    environment: {}
    healthcheck:
      test: ["CMD", "true"]
      interval: 1s
      retries: 1
      start_period: 1s

  redis:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    restart: "no"
    ports: !reset []
    volumes: !reset []
    healthcheck:
      test: ["CMD", "true"]
      interval: 1s
      retries: 1
      start_period: 1s

  # Override applelink to do nothing (use main repo's container)
  applelink:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    restart: "no"
    ports: !reset []
    volumes: !reset []
