servers:
  web:
    options:
      memory: 1g
      cpus: 1
  worker:
    options:
      memory: 1g
      cpus: 1

proxy:
  ssl: true
  host: tramline.site

accessories:
  db:
    options:
      memory: 1g
      cpus: 0.5
      restart: always
      shm-size: 64m

  redis-cache:
    cmd: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    options:
      memory: 128m
      cpus: 0.25
      restart: always

  redis-sidekiq:
    cmd: redis-server --maxmemory 100mb --maxmemory-policy noeviction --appendonly yes
    options:
      memory: 128m
      cpus: 0.25
      restart: always

  applelink:
    options:
      restart: always
      memory: 512m
      cpus: 0.5

  dozzle:
    proxy:
      ssl: true
      host: logs.tramline.site
      app_port: 8080
