servers:
  web:
    options:
      memory: 512m
  worker:
    options:
      memory: 512m

proxy:
  ssl: true
  host: tramline.site

accessories:
  db:
    options:
      memory: 256m
      restart: always
      shm-size: 64m

  redis-cache:
    cmd: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    options:
      memory: 64m
      restart: always

  redis-sidekiq:
    cmd: redis-server --maxmemory 50mb --maxmemory-policy noeviction --appendonly yes
    options:
      memory: 64m
      restart: always

  applelink:
    options:
      restart: always
      memory: 128m

  portainer:
    proxy:
      ssl: false
      host: <%= ENV["HETZNER_IP"] %>
      app_port: 9000
