refresh_external_apps:
  cron: "0 */3 * * *"
  class: "RefreshExternalAppsJob"
  active_job: true
schedule_train_releases:
  cron: "0 */12 * * *"
  class: "ScheduleTrainReleasesJob"
  active_job: true
