:verbose: true

:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 1 %>

:timeout: <%= ENV['SIDEKIQ_TIMEOUT'] || 13 %>

:queues:
  - ["high", 3]
  - ["medium", 2]
  - ["low", 1]
  - ["default", 1]

# Automatic train running is currently disabled
#
#:schedule:
#  kickoff:
#    every: "1m"
#    class: Releases::KickoffJob
#    description: "This job finds trains and/or train-steps to jump-start"
#    queue: high
