name: Deploy

on:
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: site-jobs
        run: curl -X POST https://api.render.com/deploy/${{ secrets.SITE_JOBS_PRODUCTION_SERVICE_ID }}?key=${{ secrets.SITE_JOBS_PRODUCTION_API_KEY }}
      - name: site-web
        run: curl -X POST https://api.render.com/deploy/${{ secrets.SITE_WEB_PRODUCTION_SERVICE_ID }}?key=${{ secrets.SITE_WEB_PRODUCTION_API_KEY }}
