name: Lint Schema-Dependent Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  schema-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Run schema dependency check
        run: .github/workflows/scripts/schema_lint.sh ${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
