name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  schema_deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run schema dependency check
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ruby bin/schema_lint ${{ github.base_ref }}
